name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  parent_child_checkbox: 
    git:
      url: "https://github.com/AbhishekDoshi26/parent-child-checkbox"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
