name: parent_child_checkbox
description: Parent Child Checkbox is a type of checkbox where we can establish hierarchy in Checkboxes
version: 0.0.5
homepage: https://abhishekdoshi.netlify.app
repository: https://github.com/AbhishekDoshi26/parent-child-checkbox

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: